EVAL:
    evaluate: True                  # if True, evaluate methods
    dataset: 'mini'                 # ('mini', 'tiered', 'inatural')
    arch: 'resnet18'                # ('resnet18', 'wideres')
    model_tag: 'best'               # ('final', 'best')
    method: 'paddle'                # ('paddle', 'paddle_gd', 'tim', 'alpha_tim', 'bdcspn', 'laplacianshot', 'ici', 'pt_map', 'baseline', 'baseline_pp', 'soft_km')
    k_eff: 5                        # number of different classes represented in the query
    n_ways : 'full'                 # 'full' for all test classes (i.e. K), or integer. Eg. n_ways = k_eff corresponds to the standard setting
    n_query: 75                     # total number of images in query
    shots: [5,10,20]                # number of shots for which evaluation is performed
    sampling: 'uniform'             # ('balanced' | 'dirichlet' | 'uniform') sampling of the query
    alpha_dirichlet: 1              # if sampling == 'dirichlet', dirichlet parameter
    number_tasks: 1000              # number of tasks to evaluate
    batch_size: 1000                # number of tasks per batch
    used_set_support: 'test'        # ('test', 'val') for mini and tiered, 'repr' for inatural
    used_set_query: 'test'          # ('test', 'val') for mini and tiered, 'query' for inatural
    fresh_start: False              # if False, loads the previously extracted features  
    tune_parameters: False          # if True, saves method parameter and corresponding accuracies in .txt file located at Results/params
    save_results: False             # if True, saves K_eff and corresponding accuracies in .txt file located at Results/test
    ablation: False                 # if True, convergence ablation