EVAL:
    dataset: 'mini'
    arch: 'resnet18'                # ('resnet18', 'wideres')
    evaluate: True                  # Set to True to evaluate methods
    method: 'ici'                   # ('paddle', 'paddle_gd', 'tim', 'alpha_tim', 'bdcspn', 'laplacianshot', 'ici', 'pt_map', 'baseline', 'baseline_pp', 'soft_km')
    number_tasks: 1000              # Number of tasks to evaluate
    batch_size: 1000                # Number of tasks per batch
    k_eff: 5                        # Number of different classes represented in the query
    n_ways : 5                      # 'full' for all test classes (i.e. K), or integer
    n_query: 75                     # Total number of images in query
    sampling: 'dirichlet'           # ('balanced' | 'dirichlet' | 'uniform') sampling of the query
    alpha_dirichlet: 1              # if sampling==dirichlet, dirichlet parameter
    model_tag: 'best'
    plt_metrics: ['accs']
    shots: [5,10,20]
    used_set_support: 'val'         # ('test', 'val') for mini and tiered, 'repr' for inatural
    used_set_query: 'val'           # ('test', 'val') for mini and tiered, 'query' for inatural
    fresh_start: False
    convergence_ablation: False
    tune_parameters: True
    ablation: False